packages:
  - package
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.14.4+sha512-s2H77DXhsNc/PVqdwQWt+25Z4XgeGvUFeS6l4wdt6bw96NdeAqSkHrl0bRdsQUNC5GaV4kiN3sg3FzDIZXz4Wg==
includeWorkspaceRoot: true
loglevel: info
syncInjectedDepsAfterScripts:
  - build:dev
  - build:prod
