packages:
  - package
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.14.3+sha512-ztcYj2mJN38YDHz5otQbbFBuCX9QeF1vAtIJEbCpzGe7JiCp5qv8fa+tE1nA7Xz780OjeVwTwMnBhhpMfSq4yw==
includeWorkspaceRoot: true
loglevel: info
syncInjectedDepsAfterScripts:
  - build:dev
  - build:prod
